export const INIT_ARTICLES = 'INIT_ARTICLES';
export const ADD_NEW_ARTICLE = 'ADD_NEW_ARTICLE';
export const SHOW_INTRO = 'SHOW_INTRO';
export const ADD_CUSTOM_TITLE = 'ADD_CUSTOM_TITLE';
export const EDIT_SEARCH = 'EDIT_SEARCH';
export const ADD_WALLPAPER = 'ADD_WALLPAPER';
export const REMOVE_WALLPAPER = 'REMOVE_WALLPAPER';
export const MARK_ARTICLE_FOR_EDIT = 'MARK_ARTICLE_FOR_EDIT';
