export const INIT_IMAGES = "INIT_IMAGES";
export const RESET_SEARCH = "RESET_SEARCH";

export const SET_LOCAL_QUERY = "SET_LOCAL_QUERY";
export const SEARCH_LOCAL_IMAGES = "SEARCH_LOCAL_IMAGES";

export const SET_RELEVANT_QUERY = "SET_RELEVANT_QUERY";
export const SEARCH_RELEVANT_IMAGES = "SEARCH_RELEVANT_IMAGES";


export const SET_EXTERNAL_ERROR = "SET_EXTERNAL_ERROR";

export const SET_EXTERNAL_QUERY = "SET_EXTERNAL_QUERY";
export const SEARCH_EXTERNAL_IMAGES = "SEARCH_EXTERNAL_IMAGES";
export const LOAD_MORE_EXTERNAL_IMAGES = "LOAD_MORE_EXTERNAL_IMAGES";
export const LOADING_EXTERNAL_IMAGES = "LOADING_EXTERNAL_IMAGES";

export const SELECT_EXTERNAL_IMAGE = "SELECT_EXTERNAL_IMAGE";

export const CROP_IMAGE_PREPARE = "CROP_IMAGE_PREPARE";
export const CROP_IMAGE_PENDING = "CROP_IMAGE_PENDING";
export const CROP_IMAGE = "CROP_IMAGE";
