"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CROP_IMAGE = exports.CROP_IMAGE_PENDING = exports.CROP_IMAGE_PREPARE = exports.SELECT_EXTERNAL_IMAGE = exports.LOAD_MORE_EXTERNAL_IMAGES = exports.SEARCH_EXTERNAL_IMAGES = exports.SET_EXTERNAL_QUERY = exports.SEARCH_RELEVANT_IMAGES = exports.SET_RELEVANT_QUERY = exports.SEARCH_LOCAL_IMAGES = exports.SET_LOCAL_QUERY = exports.RESET_SEARCH = exports.INIT_IMAGES = void 0;
exports.INIT_IMAGES = "INIT_IMAGES";
exports.RESET_SEARCH = "RESET_SEARCH";
exports.SET_LOCAL_QUERY = "SET_LOCAL_QUERY";
exports.SEARCH_LOCAL_IMAGES = "SEARCH_LOCAL_IMAGES";
exports.SET_RELEVANT_QUERY = "SET_RELEVANT_QUERY";
exports.SEARCH_RELEVANT_IMAGES = "SEARCH_RELEVANT_IMAGES";
exports.SET_EXTERNAL_QUERY = "SET_EXTERNAL_QUERY";
exports.SEARCH_EXTERNAL_IMAGES = "SEARCH_EXTERNAL_IMAGES";
exports.LOAD_MORE_EXTERNAL_IMAGES = "LOAD_MORE_EXTERNAL_IMAGES";
exports.SELECT_EXTERNAL_IMAGE = "SELECT_EXTERNAL_IMAGE";
exports.CROP_IMAGE_PREPARE = "CROP_IMAGE_PREPARE";
exports.CROP_IMAGE_PENDING = "CROP_IMAGE_PENDING";
exports.CROP_IMAGE = "CROP_IMAGE";
//# sourceMappingURL=images-actions.js.map